--
-- Incident staging table
--
CREATE TABLE public.incident_staging_tbl (
    incident_id character varying,
    input_data character varying,
    inserted_at bigint,
    source character varying
);

ALTER TABLE public.incident_std_tbl add column sla_value bigint;
ALTER TABLE public.incident_std_tbl add column latest_ticket_resolution_at bigint;

INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Database', 'Database instance down', NULL, NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Backup', 'DB backup Failed /Missed', 'Typically, it indicates that DB backup is either failed or missed. This could be a job failure or manual error while taking DB backup.
This may lead to dependent application or services losing its value as the very data it uses for different purposes is unavailable. This may also impact data recovery operation with respect to database as physical backup itself is not present.
Typically this may be because of database integrity check found integrity errors, change made in backup user ID with regards to the user name / password used by backup job, communication error between backup agent and backup server, schedule service down, Media (scratch tapes) are not available or failed or DB backup operation is in pending state because data paths are either offline or busy.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Backup', 'VM backup Failed /Missed', 'Typically, it indicates that VM backup is either failed or missed.
Unavailability of VM may impact the core functionality or business output directly. In some cases, the productivity of the business unit goes down if the VM backup is not available.
This maybe because of VM is not present in Vcenter /ESXi host, VM consolidation issue, communication issue between Vcenter and backup tool, Snapshot disable from VCenter end or Permission issue on VCenter.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Data Transfer', 'Socket Timeout', 'Typically seen in a monitoring setup , when a monitored asset is not accessible by or not responding to a monitoring server over prolonged time.
This may result in loss of visibility with respect to health or performance of the monitored assets.
Usually this is result of loss of connection between server and the  monitored asset which could be due to network issues between the two or monitored assets itself being not availabl or down.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Backup', 'File backup Failed /Missed', 'Typically it indicates that file backup job is either failed or missed.
This results into unavailability of the backup of the files for that duration which in turn means that the data cannot be recovered for that specific period in case of any unfortunate event.
This may happen either because the resource selected for backup is no longer exist in the environment, File /folder is right protected by application, open files, overlaps (long running ) backup for network drive, or  changes made in Active directory or workgroup with regards to the User name or password used by backup job.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Backup', 'Request to Backup', 'User requested for backup or archive.
Usually user request to add servers in daily schedule backup job or one time backup before any specific activity or for long turn retention archive backup.   ', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Health Check', 'Cluster Alert', NULL, NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Database', 'Status Unknown', NULL, NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Database', 'Connection Failure', NULL, NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Database', 'Oracle-Miscellaneous', NULL, NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Database', 'ORA-00445:Background process', NULL, NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Database', 'High Connection count', NULL, NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Database', 'Mongo - Miscellaneous', NULL, NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Database', 'SQL Server - Miscellaneous', NULL, NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Database', 'Cluster Failover', 'This indicates that the resources failed over from one node to another
Issues with Cluster Failover impacts high availability
There are multiple reasons for it to fail but the most likely cause is network or performance issues', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Database', 'Blocked Session', 'This indicates that stale sessions are clogging the resources
Issues with Blocked session would lead to resource crunch
There are multiple reasons for it to fail but the most likely cause is cache issues', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Domain Controller', 'FRSSysVol in Critical State', 'This indicates that the File Replication Service is failing on the Domain Controller.
Issue with this servicve would lead to file  & permission updates to fail.
There are multiple reasons for it to fail but the most likely cause is network or space problems.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Domain Controller', 'Replications in Critical State ', 'This indicates that the Replication is failing between the Domain Controllers.
Issues with replication would lead to Active Directory data to be outdated.
There are multiple reasons for it to fail but the most likely cause is network or time sync problems.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Domain Controller', 'Advertising in Critical State ', 'This indicates that the Domain Controller isnt advertising the roles that it is capable of performing
Issues with advertising would lead to unavailability of Active Directory services.
There are multiple reasons for it to fail but the most likely cause is Netlogon services failed to start.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Domain Controller', 'Replication Errors Reported ', 'This indicates that the Replication is failing between the Domain Controllers.
Issues with replication would lead to Active Directory data to be outdated.
There are multiple reasons for it to fail but the most likely cause is network or time sync problems.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Domain Controller', 'No errors reported', 'This indicates that the Replication is failing between the Domain Controllers.
Issues with replication would lead to Active Directory data to be outdated.
There are multiple reasons for it to fail but the most likely cause is network or time sync problems.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Storage', 'Disk Quota Exceeded', 'This indicates that the Disk usage has crossed the limits
Issues with this would lead to space cruch
There are multiple reasons for it to quota to exceed but the most likely cause is temp files or page file', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Storage', 'Unity-Replication Error', NULL, NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Storage', 'Unity-Cannot connect to CEPA', NULL, NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Storage', 'Unity-Unable to connect to EMC', NULL, NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Storage', 'Unity-Storage Full', NULL, NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Tivoli Workload Scheduler (TWS)', 'TWS Agent Down', 'Seen on TWS Workstations, if either or both of TWS Writer Running and Agent Running are down
The TWS jobs/job streams that the TWS Workstation responsible for will be impacted
The workstation resources may be swamped or the TWS related services may be hung causing the issue', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Windows', 'Print Spooler Service down', 'Indicates that windows print spooler service is down or unavailable.
Consequently, printing capabilities of windows is not working.
Usually this problem occurs because of an access violation in the printer-driver process. When this problem occurs, the spooler does not stop, and the SPM port does not reset resulting in print queue to crash.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Windows', 'Reboot', 'This indicates that the server/application hung or requested by Key client/server owner
Issues with Server/application hung may impact the production
There are multiple reasons for it to spike but the most likely cause high cpu & memory utilization.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Email Administration', 'Email Pull', NULL, NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Domain Controller', 'Connection Failure', 'This indicates that the Connection to Active Directory services is failing.
Issues with connection would lead to unavailability of Active Directory services.
There are multiple reasons for it to fail but the most likely cause is network or port issues', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Email Administration', 'Block Sender', NULL, NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Domain Controller', 'Replication Queue status', 'This indicates that the File Replication Service is failing on the Domain Controller.
Issue with this servicve would lead to file  & permission updates to fail.
There are multiple reasons for it to fail but the most likely cause is network or space problems.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Domain Controller', 'Replication Health OK', 'This indicates that the Replication has recovered from an transient failure between the Domain Controllers.
Issues with replication would lead to Active Directory data to be outdated.
There are multiple reasons for it to fail but the most likely cause is network or time sync problems.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Tivoli Workload Scheduler (TWS)', 'TWS Abend', 'Seen on TWS monitoring, where a job/s error out
The TWS job/s will be impacted is the issue isnt fixed
The TWS job configuration is the cause of the issue', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Domain Controller', 'Services in Critical State', 'This indicates that the Connection to Active Directory services is failing.
Issues with connection would lead to unavailability of Active Directory services.
There are multiple reasons for it to fail but the most likely cause is network or port issues', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Domain Controller', 'Intersite in Critical State', 'This indicates that the Intersite replication is failing between Domain Controller
Issues with Intersite would lead to unavailability of Active Directory services.
There are multiple reasons for it to fail but the most likely cause is network or port issues', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Domain Controller', 'MachineAccount in Critical State ', 'This indicates that the MachineAccount for the Domain Controller isnt advertising the Active Directory Services
Issues with MachineAccount would lead to unavailability of Active Directory services.
There are multiple reasons for it to fail but the most likely cause is network or port issues', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Health Check', 'MTVNE Morning Checks', 'VIMN team raised incident to perform daily backup health check.        Monitor any backup failuer and backup completed status.  Health Check are used to ensure compliance with auditors and RPO/RTO, business continuity, and end-user data safety', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Infrastructure', 'Hardware Alert', 'This may happen when monitoring tool reports for any hardware fault like power supply failure, fan failure, etc.
This may lead to the device down and may impact the users, applications, and other services running/connected to the device.
This may happen because of a hardware issue (physical) with the device.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Monitoring', 'Host Not Reporting/Down', 'This happens when the monitoring tool is not able to reach to devices.
This may impact the users, applications, and other services running/connected to the device.
This may happen due to the power issue with the device, ISP issue at the site, fault with uplink cables/equipment.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Monitoring', 'Service Connection refused', 'This indicates some network or port related failure. This may result in loss of visibility with respect to health or performance of the monitored assets.
. Disabling the firewall works in most the cases ', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Monitoring', 'NRPE Error-SSL Handshake', 'Typically seen that connection timeout between nagios server & SSL or HTTPS service of server.                                                     This may result in loss of visibility with respect helath of servvice of monitored assest.                                     Usually this is result of loss of connection between SSL service of server and the  monitored asset which could be due to network issues between the two or monitored assets itself being not available or down.   ', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Monitoring', 'NRPE Error-Connection Failure', 'Typically seen in a monitoring setup , when a monitored asset is not accessible by or not responding to a monitoring server over prolonged time.
This may result in loss of visibility with respect to health or performance of the monitored assets.
Usually this is result of loss of connection between server and the  monitored asset which could be due to network issues between the two or monitored assets itself being not availabl or down.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Monitoring', 'NRPE Error - Socket Timeout', NULL, NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Network', 'Device Up', 'refer INC #INC03574553, Bhawesh open INC to check whether any alerts regarding host not reporting. we have no seeing any events(alerts) And it is able to monitor cpu memory...etc.                                               We have to installed New relic on solaris server', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Network', 'Device Down/Reboot', 'This happens when the monitoring tool sees finds that any particular device is rebooted
This may impact the users, applications, and other services running/connected to the device.
This may happen due to a power issue with the device at that particular location.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Network', 'Interface Errors', 'This is due to the increase in the errors on the interfaces monitored.
This may lead to a performance issue like network slowness.
This may be due to loose cabling, defective cables or ports, overutilization of the bandwidth of the interface.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Performance - Server/OS', 'High Disk Utilization', 'Indicative of  high disk usage/utilization on an asset/server  which is being monitored for performance.
If this situation persists, it may impact the performance or availability of dependent services or application.
Typically a result of high volume of data stored on the disk.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Performance - Server/OS', 'High CPU Utilization', 'Indicative of  high CPU usage  or utilization on an asset or server  which is being monitored for performance.
If this situation persists, it may impact the performance or availability of dependent services or application.
Typically a CPU surge is a result of complex  CPU intensive processing or an unoptimized process that is consuming CPU more than expected or too many running processes leading to high CPU consumption.', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Performance - Server/OS', 'High Memory Utilization', 'This indicates that the Memory consumption is high
Issues with high Memory utilization would impacts performance of OS
There are multiple reasons for it to spike but the most likely cause is memory leaks', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);
INSERT INTO public.category_master_tbl (category_1_name, category_2_name, description, sop_count, category_selection_count, category_prediction_count, category_top_prediction_count, status, comments, approved_at, approved_by, suggested_id, created_at, created_by, updated_at, is_certified, is_manually_added) VALUES ('Performance - Server/OS', 'Load Average', 'This indicates that the CPU or Memory consumption is high
Issues with high CPU or Memoryy utilization would impacts performance of OS
There are multiple reasons for it to spike but the most likely cause is memory leaks', NULL, 0, 0, 0, 'Published', NULL, NULL, NULL, NULL, 1589543247, NULL, NULL, true, false);